name: Test Everything on macOS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: ./gradlew wasmJsTest
        continue-on-error: true
      - name: Run tests
        run: ./gradlew watchosSimulatorArm64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew iosSimulatorArm64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew wasmJsNodeTest
        continue-on-error: true
      - name: Run tests
        run: ./gradlew wasmJsBrowserTest
        continue-on-error: true
      - name: Run tests
        run: ./gradlew tvosX64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew tvosSimulatorArm64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew testReleaseUnitTest
        continue-on-error: true
      - name: Run tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: true
      - name: Run tests
        run: ./gradlew mingwX64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew macosX64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew macosArm64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew linuxX64Test
        continue-on-error: true
      - name: Run tests
        run: ./gradlew iosX64Test
        continue-on-error: true
      - name: List reports
        run: ls -la shared/build/test-results/bolted-on
        if: success() || failure()
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: All Tests
          path: shared/build/test-results/**/TEST*.xml
          reporter: java-junit
          use-actions-summary: true