name: Test Everything on macOS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: ./gradlew jvmTest wasmJsTest watchosSimulatorArm64Test iosSimulatorArm64Test wasmJsNodeTest wasmJsBrowserTest tvosX64Test tvosSimulatorArm64Test testReleaseUnitTest testDebugUnitTest mingwX64Test macosX64Test macosArm64Test linuxX64Test iosX64Test
      - name: List reports
        run: ls -la shared/build/test-results/bolted-on
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: All Tests
          path: shared/build/test-results/**/TEST*.xml
          reporter: java-junit
          use-actions-summary: true