name: Test Everything
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: ./gradlew allTests
      - name: List reports
        run: ls -la shared/build/kotest-reports
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: All Tests
          path: shared/build/kotest-reports/*.xml
          reporter: java-junit